# Generated by Django 3.2 on 2022-05-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayed_university_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='zayed_university_app_log',
        ),
    ]
